server:
  port: 8081
  servlet:
    context-path: /user/ # 对外接口前缀

logging:
  config: classpath:log.xml # log配置文件

mybatis-plus:
  configuration:
    cache-enabled: false # 关闭二级缓存
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开始sql打印

spring:
  application:
    name: lxz-user
  profiles:
    active: @spring.profile@
  messages:
    basename: i18n/error/message,i18n/error/description,i18n/error/solution # user系统 1 开头 四位码值 10001
  flyway:
    locations: classpath:db/migration
    table: flyway_schema_history_user # 不同微服务用自己的flyway表防止冲突
    baseline-on-migrate: true # 不同模块公用的一个schema但是flyway table不同，所以需要开启这个配置，允许flyway在非空schema创建管理表
  datasource:
    url: jdbc:mysql://localhost:3306/lxz
    username: aoi
    password: 131747hu
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        group: hjx
        namespace: dev
      config:
        server-addr: 127.0.0.1:8848
        namespace: dev
  config:
    import:
      - nacos:user?group=dev

